### ISSUE TITLE
Add acceptance tests to cover MODULES-111888 scenario  for IIS applications

### ISSUE THREAD

**Issue by chelnak** [puppetlabs/puppetlabs-iis#337]
## Use Case

There should be at minimum one test case that covers the scenario where an existing physical path exists with a `/` at the end.

The test(s) can be added to the following spec:

https://github.com/puppetlabs/puppetlabs-iis/blob/main/spec/acceptance/iis_application_spec.rb

## Describe the Solution You Would Like
N/A

## Describe Alternatives You've Considered
N/A

## Additional Context
N/A

**Comment by david22swan** [comment]
Held up by failures on the main branch.
Error's seem to be originating from an inability to clone down the required fixtures, this does not seem to be replicated within any other module.
